spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      use-new-id-generator-mappings: 'true'
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/SpringChat
    username: root
    password: fireice22072001
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true

